language: go
go:
 - 1.13.x

git:
  depth: 1

script:
 - go test -covermode=count -coverprofile=count.out
 
 after_success:
 - go get -v github.com/mattn/goveralls
 - goveralls -coverprofile=count.out -service=travis-ci
